# Generated by Django 3.2.2 on 2021-05-07 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=64, unique=True)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('password', models.CharField(max_length=255)),
                ('register_date', models.DateTimeField(auto_now_add=True)),
                ('signature', models.CharField(blank=True, max_length=255, null=True, verbose_name='签名')),
            ],
        ),
    ]
