# Generated by Django 3.2.2 on 2021-05-07 15:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0004_articleupdown'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('nid', models.AutoField(primary_key=True, serialize=False)),
                ('create_time', models.DateTimeField(auto_now_add=True)),
                ('content', models.TextField()),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app01.article')),
                ('parent_comment', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app01.comment')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app01.account')),
            ],
        ),
    ]
